import { DEFAULTS, normalizeSettings, readSettings, uiLocale, TOOLBAR_ACTIONS, hiddenToolbarActions } from '../core/settings.js';
import { languageChoices } from '../shared/ocr-languages.js';
const copy={
'en-US':{title:'Settings',intro:'Make Cosmic PDF feel right for the way you read.',open:'Open a PDF',reset:'Reset settings',confirm:'Reset all Cosmic PDF settings?',saved:'Saved',error:'Could not save. Please try again.',privacy:'PDFs and OCR stay on this device. There is no upload, analytics or cloud recognition. Rendering and OCR changes apply to PDFs opened or reloaded afterward.',groups:['Opening & appearance','Reading & rendering','Text recognition'],
labels:{enabled:['Open PDFs with Cosmic PDF','Automatically open supported PDF links in this reader. Downloads remain downloads.'],locale:['Interface language','Choose the language used in the reader and Settings.'],appearance:['Appearance','Choose a light or dark theme, or follow your browser.'],sampling:['Rendering quality','Higher sampling makes text and fine details sharper but uses more memory.'],sharpening:['Sharpen page images','Apply mild sharpening. This uses additional graphics memory.'],zoom:['Default zoom','Set the initial size of each newly opened PDF.'],gap:['Page spacing','Adjust the space between pages.'],toolbar:['Toolbar content','Choose what appears in the toolbar.'],toolbarHidden:['More actions','Move selected controls into the More actions menu.'],sidebar:['Show page thumbnails on opening','Keep the page navigator open when a document starts.'],links:['Allow document links','Enable clickable links to web pages and email addresses.'],motion:['Interface animation','Animate loading indicators and small interface transitions.'],darkStrength:['Dark theme depth','Choose how dark the paper appears.'],ocrLanguages:['OCR languages','Select one or more languages to recognize.'],ocrQuality:['OCR detail','Use higher detail for small text. Recognition runs only when you request it.'],ocrLayout:['OCR layout','Choose the layout that best describes the scanned page.'],ocrOverlay:['Select recognized text on pages','Place a selectable text layer over recognized pages. The original PDF stays unchanged.']},
tools:{pages:'Pages and outline',find:'Find in document',paging:'Previous/next page',zoom:'Zoom out/in',fit:'Fit width/page',rotate:'Rotate left',fullscreen:'Full screen',ocr:'Text recognition',print:'Print',properties:'Document properties',native:'Use Chrome reader'},
values:{toolbarBranding:'Cosmic PDF branding',toolbarFilename:'Filename',auto:'Auto',light:'Light',dark:'Dark',english:'English',chinese:'简体中文',fitWidth:'Fit width',fitPage:'Fit page',px:'px',soft:'Soft',balanced:'Balanced',deep:'Deep',black:'Black',eng:'English',sim:'Simplified Chinese',tra:'Traditional Chinese',fast:'Fast',standard:'Balanced',fine:'Fine',layoutAuto:'Automatic',block:'Single text block',sparse:'Scattered text'}},
'zh-CN':{title:'设置',intro:'按照您的阅读习惯调整 Cosmic PDF。',open:'打开 PDF',reset:'重置设置',confirm:'是否重置 Cosmic PDF 的所有设置？',saved:'已保存',error:'保存失败，请重试。',privacy:'PDF 和 OCR 均在本机处理，不上传文件，不提供云端识别，也不收集使用数据。显示与 OCR 设置的修改适用于之后打开或刷新的 PDF。',groups:['打开方式与外观','阅读与显示','文字识别'],
labels:{enabled:['使用 Cosmic PDF 打开 PDF','自动接管支持的 PDF 阅读链接，不改变正常的文件下载。'],locale:['界面语言','选择阅读器和设置页的语言。'],appearance:['外观','选择浅色、深色，或跟随浏览器。'],sampling:['显示清晰度','提高采样倍数可改善文字和细节，但会增加内存占用。'],sharpening:['锐化页面图像','进行轻度锐化，此选项会增加图形内存占用。'],zoom:['默认缩放','设置新打开 PDF 的初始显示比例。'],gap:['页面间距','调整页面之间的空隙。'],toolbar:['工具栏内容','选择在工具栏中显示的内容。'],toolbarHidden:['更多操作','将勾选的工具收纳到“更多操作”菜单中。'],sidebar:['打开时显示页面缩略图','在打开文档时展开页面导航栏。'],links:['允许文档链接','允许点击文档中的网页链接和电子邮件地址。'],motion:['界面动画','显示加载指示和轻量界面动画。'],darkStrength:['深色模式深度','调整深色模式下的纸张深浅。'],ocrLanguages:['OCR 语言','勾选需要识别的语言，至少选择一项。'],ocrQuality:['OCR 精细程度','小字较多时可提高精细程度，仅在您主动操作后开始识别。'],ocrLayout:['OCR 排版','选择最符合扫描页面的文字排版。'],ocrOverlay:['在页面上选择识别文字','在识别后的页面上添加可选中的文字层，不修改原 PDF。']},
tools:{pages:'页面和目录',find:'在文档中查找',paging:'上一页／下一页',zoom:'缩小／放大',fit:'适合宽度／适合页面',rotate:'向左旋转',fullscreen:'全屏',ocr:'文字识别',print:'打印',properties:'文档信息',native:'使用 Chrome 阅读器'},
values:{toolbarBranding:'Cosmic PDF 标识',toolbarFilename:'文件名',auto:'自动',light:'浅色',dark:'深色',english:'English',chinese:'简体中文',fitWidth:'适合宽度',fitPage:'适合页面',px:'像素',soft:'柔和',balanced:'适中',deep:'深黑',black:'纯黑',eng:'英文',sim:'简体中文',tra:'繁体中文',fast:'快速',standard:'均衡',fine:'精细',layoutAuto:'自动',block:'单一文本块',sparse:'分散文字'}}};
let state=await readSettings(),queue=Promise.resolve();const $=id=>document.getElementById(id);
function render(){const locale=uiLocale(state,chrome.i18n.getUILanguage()),t=copy[locale],v=t.values;document.documentElement.lang=locale;document.title='Cosmic PDF · '+t.title;
 document.documentElement.dataset.dark=String(state.appearance==='dark'||(state.appearance==='auto'&&matchMedia('(prefers-color-scheme:dark)').matches));try{localStorage.setItem('appearance',state.appearance);}catch{}
 for(const [id,key] of [['title','title'],['intro','intro'],['open-reader','open'],['reset','reset'],['privacy','privacy']])$(id).textContent=t[key];
 const options={locale:[['auto',v.auto],['en-US',v.english],['zh-CN',v.chinese]],appearance:[['auto',v.auto],['light',v.light],['dark',v.dark]],sampling:[1,2,3,4,5,6].map(n=>[n,n+'×']),zoom:[['page-width',v.fitWidth],['page-fit',v.fitPage],...[.5,.75,1,1.25,1.5,2].map(n=>[String(n).replace(/^0\./,'.'),n*100+'%'])],gap:[8,16,24,32].map(n=>[n,n+' '+v.px]),darkStrength:[[.85,v.soft],[.9,v.balanced],[.96,v.deep],[1,v.black]],ocrQuality:[[1.5,v.fast],[2,v.standard],[3,v.fine]],ocrLayout:[['3',v.layoutAuto],['6',v.block],['11',v.sparse]]};
 const groupKeys=[['enabled','locale','appearance','toolbar','toolbarHidden'],['sampling','sharpening','zoom','gap','sidebar','links','motion','darkStrength'],['ocrLanguages','ocrQuality','ocrLayout','ocrOverlay']];
 $('groups').replaceChildren();groupKeys.forEach((keys,i)=>{const section=document.createElement('section'),h=document.createElement('h2'),card=document.createElement('div');h.textContent=t.groups[i];card.className='card';section.append(h,card);
 for(const key of keys){const row=document.createElement('div'),desc=document.createElement('div'),title=document.createElement('h3'),p=document.createElement('p');row.className='row';title.id=key+'-title';p.id=key+'-help';title.textContent=t.labels[key][0];p.textContent=t.labels[key][1];desc.append(title,p);let input;
 if(key==='toolbar'){
  const fieldset=document.createElement('fieldset'),options=document.createElement('div');fieldset.id='toolbar';fieldset.className='language-choices';fieldset.setAttribute('aria-labelledby',title.id);fieldset.setAttribute('aria-describedby',p.id);options.className='language-options';row.classList.add('languages');
  for(const [setting,label]of [['showFilename',v.toolbarFilename],['showBranding',v.toolbarBranding]]){const choice=document.createElement('label'),checkbox=document.createElement('input'),caption=document.createElement('span');checkbox.type='checkbox';checkbox.id=setting;checkbox.checked=state[setting];caption.textContent=label;checkbox.onchange=()=>save(setting,checkbox.checked);choice.append(checkbox,caption);options.append(choice);}
  fieldset.append(options);row.append(desc,fieldset);card.append(row);continue;
 }
 if(key==='toolbarHidden'){
  row.classList.add('toolbar-options');const fieldset=document.createElement('fieldset');fieldset.id=key;fieldset.className='language-choices';fieldset.setAttribute('aria-labelledby',title.id);fieldset.setAttribute('aria-describedby',p.id);
  const options=document.createElement('div');options.className='language-options';const hidden=new Set(hiddenToolbarActions(state));
  for(const action of TOOLBAR_ACTIONS){const label=document.createElement('label'),checkbox=document.createElement('input'),caption=document.createElement('span');checkbox.type='checkbox';checkbox.id='hide-'+action;checkbox.checked=hidden.has(action);caption.textContent=t.tools[action];checkbox.onchange=()=>save(key,{[action]:checkbox.checked});label.append(checkbox,caption);options.append(label);}
  fieldset.append(options);row.append(desc,fieldset);card.append(row);continue;
 }
 if(key==='ocrLanguages'){const fieldset=document.createElement('fieldset');fieldset.id=key;fieldset.className='language-choices';fieldset.setAttribute('aria-labelledby',title.id);fieldset.setAttribute('aria-describedby',p.id);row.classList.add('languages');languageChoices(fieldset,state.ocrLanguages,{eng:v.eng,chi_sim:v.sim,chi_tra:v.tra},value=>save(key,value));row.append(desc,fieldset);card.append(row);continue;}
 if(typeof DEFAULTS[key]==='boolean'){input=document.createElement('input');input.type='checkbox';input.checked=state[key];input.setAttribute('role','switch');}else{input=document.createElement('select');for(const [value,label]of options[key]){const option=document.createElement('option');option.value=value;option.textContent=label+((i>0||key==='appearance')&&value===DEFAULTS[key]?(locale==='zh-CN'?'（默认）':' (default)'):'');input.append(option);}input.value=state[key];}
 input.id=key;input.setAttribute('aria-labelledby',title.id);input.setAttribute('aria-describedby',p.id);input.onchange=()=>{let value=input.type==='checkbox'?input.checked:input.value;if(typeof DEFAULTS[key]==='number')value=Number(value);save(key,value);};row.append(desc,input);card.append(row);} $('groups').append(section);});
}
function save(key,value){queue=queue.catch(()=>{}).then(async()=>{const latest=await readSettings(),next=normalizeSettings({...latest,[key]:key==='toolbarHidden'?{...latest.toolbarHidden,...value}:value});await chrome.storage.local.set({settings:next});const result=await chrome.runtime.sendMessage({type:'SETTINGS_SAVED'});if(!result?.ok)throw Error('rules');state=next;if(key==='showFilename'||key==='showBranding'){const hidden=new Set(hiddenToolbarActions(state));for(const action of TOOLBAR_ACTIONS)$('hide-'+action).checked=hidden.has(action);}if(key==='locale'||key==='appearance')render();$('saved').textContent=copy[uiLocale(state,chrome.i18n.getUILanguage())].saved;}).catch(()=>{$('saved').textContent=copy[uiLocale(state,chrome.i18n.getUILanguage())].error;});}
$('open-reader').onclick=()=>void chrome.tabs.create({url:chrome.runtime.getURL('workspaces/pdf-reader/index.html')});
$('reset').onclick=()=>{const t=copy[uiLocale(state,chrome.i18n.getUILanguage())];if(confirm(t.confirm))queue=queue.catch(()=>{}).then(async()=>{await chrome.storage.local.set({settings:{...DEFAULTS}});await chrome.runtime.sendMessage({type:'SETTINGS_SAVED'});state={...DEFAULTS};render();$('saved').textContent=copy[uiLocale(state,chrome.i18n.getUILanguage())].saved;}).catch(()=>{$('saved').textContent=t.error;});};
matchMedia('(prefers-color-scheme:dark)').addEventListener('change',()=>{if(state.appearance==='auto')document.documentElement.dataset.dark=String(matchMedia('(prefers-color-scheme:dark)').matches);});render();

// Refresh file-scheme eligibility when the settings page is reopened.
void chrome.runtime.sendMessage({type:'SETTINGS_SAVED'}).catch(()=>{});
